# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install .NET SDK (if needed for your project)
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
  displayName: 'Install .NET SDK'

# Install OWASP ZAP
- script: |
    sudo apt-get update
    sudo apt-get install -y wget openjdk-11-jre
    wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2_15_0_unix.sh
    chmod +x ZAP_2_15_0_unix.sh
    sudo ./ZAP_2_15_0_unix.sh -q -dir /opt/zap
    if [ -L /usr/local/bin/zap.sh ]; then
        sudo rm /usr/local/bin/zap.sh
    fi
    sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap.sh
  displayName: 'Install OWASP ZAP'
  
  # Install zap-cli
- script: |
    sudo apt-get install -y python3-pip
    pip3 install zapcli
  displayName: 'Install zap-cli'

# Run ZAP OWASP Scan
- script: |
    /opt/zap/zap.sh -daemon -host 127.0.0.1 -port 8080
    sleep 60  # Wait for ZAP to start
    zap-cli status -t 120  # Wait up to 2 minutes for ZAP to be ready
    zap-cli open-url https://www.t2mlab.com/
    zap-cli spider https://www.t2mlab.com/
    zap-cli active-scan https://www.t2mlab.com/
    zap-cli report -o owaspzap/report.json -f json
    zap-cli report -o owaspzap/report.html -f html
  displayName: 'Run ZAP OWASP Scan'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
